### ISSUE TITLE
Can't hide the bar

### ISSUE THREAD

**Issue by fallais** [aitboudad/ngx-loading-bar#144]
Hello,

this does not work : `<ngx-loading-bar color="#E3E3E3" diameter="20px" includeBar="false"></ngx-loading-bar>
`

Am I missing something ?

**Comment by aitboudad** [comment]
use: `[includeBar]="false"`

**Comment by fallais** [comment]
It is working, thanks a lot ! But why `[includeBar]="false"` and for example not `[color]="#E3E3E3"` ?

**Comment by aitboudad** [comment]
when passing an attribute without binding the passed value is evaluated as `string` value:

- `color="#E3E3E3"`: the `color` receive `"#E3E3E3"` which is valid
- `[color]="#E3E3E3"`: angular evalute the passed value as undefined (expect a defined variable), in that case it should be wrapped by quote: `[color]="'#E3E3E3'"` in order to work.
- `includeBar="false"`: the `includeBar` receive `"false"` instead of `false` but I think we can support both cases.
