### ISSUE TITLE
Loading bar on routing doens't appear

### ISSUE THREAD

**Issue by fabioformosa** [aitboudad/ngx-loading-bar#166]
I've followed instructions to display the loading bar at routing, but it doesn't appear.
So I've tested  your demo (https://angular-sypacw.stackblitz.io/) and I don't see any loading bar clicking on page '/' and page'/test'.

Is it a bug or didn't I understand something?

Downgrading to version 4.x, all it's fine.

(I'm using angular 9)

**Comment by aitboudad** [comment]
That's a new behavior that is added in `v5` when navigation end before the loading-bar start which took ~250 ms the loading bar won't be displayed.

**Comment by maciej-laskowski** [comment]
@aitboudad Perhaps this behaviour should be mentioned in the documentation? Is there a way to alter/disable this?

**Comment by aitboudad** [comment]
Not sure which behavior should be the default one and I don't mind to rollback that behavior and allow more customization on that part since is not documented yet.

**Comment by maciej-laskowski** [comment]
@aitboudad I am afraid that this new default might be counter-intuitive for new ngx-loading-bar users especially that developers working on local development servers will rarely exceed the 250ms threshold. I also upgraded to 5.x and rolled back because the loading bar didn't seem to work and I didn't have time to investigate.

I think documenting this "activation threshold" feature and allowing to customise and disable it would be much needed.

**Comment by aitboudad** [comment]
fixed in [v5.1.0](https://github.com/aitboudad/ngx-loading-bar/releases/tag/v5.1.0)
