### ISSUE TITLE
includeSpinner and includeBar not working

### ISSUE THREAD

**Issue by LuckeeDev** [aitboudad/ngx-loading-bar#168]
Not sure if this just my problem, but the includeSpinner and includeBar options are not working for me (first time trying this, so I might be doing something wrong).

These are the steps that led me to this problem (Angular version:  9.1.4):

- I installed the router package with `npm install @ngx-loading-bar/core @ngx-loading-bar/router --save`

- I correctly included the `LoadingBarRouterModule` in my `app.module.ts`

- I added the `<ngx-loading-bar></ngx-loading-bar>` between my `app-navbar` and my `router-outlet`

- I tried changing some options (which worked) doing: `<ngx-loading-bar color="#9cf" fixed="false"></ngx-loading-bar>` 

- at last, I tried changing the includeSpinner and includeBar options with `<ngx-loading-bar includeSpinner="false"></ngx-loading-bar>` and `<ngx-loading-bar includeBar="false"></ngx-loading-bar>`, but neither of them actually hid the spinner or the bar, leaving both of them visible.

Is this a bug or am I doing something wrong? Thanks in advance for your time :)

**Comment by abinici** [comment]
@LuckeeDev 

I dont know if you have solved this yourself, but I experienced the same issue. But then I remembered that passing a parameter like this `<ngx-loading-bar includeSpinner="false">` is interpreted like a string and because its not an empty string it will be truthy. You have to use binding like this to make it understand the boolean value `<ngx-loading-bar [includeSpinner]="false">`.
